"""Add borrowed_date to book_copy

Revision ID: 93d334513f5b
Revises: 1561a4a2cc8b
Create Date: 2025-05-04 12:04:21.019591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d334513f5b'
down_revision: Union[str, None] = '1561a4a2cc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_copies', sa.Column('borrowed_date', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'book_copies', 'users', ['user_id'], ['user_id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_copies', type_='foreignkey')
    op.drop_column('book_copies', 'borrowed_date')
    # ### end Alembic commands ###
