"""Change field 'desc' to 'description'

Revision ID: d9ba80028dcd
Revises: 40032e55006b
Create Date: 2025-03-24 14:40:51.546213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ba80028dcd'
down_revision: Union[str, None] = '40032e55006b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'book_copies', 'users', ['user_id'], ['user_id'], ondelete='SET NULL', use_alter=True)
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('books', 'desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('books', 'description')
    op.drop_constraint(None, 'book_copies', type_='foreignkey')
    # ### end Alembic commands ###
